/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChromeRouteImport } from './routes/chrome'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as SocialRouteImport } from './routes/social'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/chrome',
  path: '/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/chrome': typeof ChromeRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/logos': typeof LogosRoute
  '/marks': typeof MarksRoute
  '/patterns': typeof PatternsRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/chrome': typeof ChromeRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/logos': typeof LogosRoute
  '/marks': typeof MarksRoute
  '/patterns': typeof PatternsRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/chrome': typeof ChromeRoute
  '/components': typeof ComponentsRoute
  '/foundations': typeof FoundationsRoute
  '/logos': typeof LogosRoute
  '/marks': typeof MarksRoute
  '/patterns': typeof PatternsRoute
  '/social': typeof SocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/chrome'
    | '/components'
    | '/foundations'
    | '/logos'
    | '/marks'
    | '/patterns'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/chrome'
    | '/components'
    | '/foundations'
    | '/logos'
    | '/marks'
    | '/patterns'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/chrome'
    | '/components'
    | '/foundations'
    | '/logos'
    | '/marks'
    | '/patterns'
    | '/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  ChromeRoute: typeof ChromeRoute
  ComponentsRoute: typeof ComponentsRoute
  FoundationsRoute: typeof FoundationsRoute
  LogosRoute: typeof LogosRoute
  MarksRoute: typeof MarksRoute
  PatternsRoute: typeof PatternsRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome': {
      id: '/chrome'
      path: '/chrome'
      fullPath: '/chrome'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  ChromeRoute: ChromeRoute,
  ComponentsRoute: ComponentsRoute,
  FoundationsRoute: FoundationsRoute,
  LogosRoute: LogosRoute,
  MarksRoute: MarksRoute,
  PatternsRoute: PatternsRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
